[workspace]
name = "habitat-sim"
channels = ["conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[pypi-dependencies]
habitat-sim = { path = ".", editable = true }

[package.build.backend]
name = "pixi-build-python"
version = "*"
channels = ["https://prefix.dev/conda-forge"]

[package]
name = "habitat_sim"
version = "0.2.3"

[package.host-dependencies]
cmake = ">=3.2,<4"
ninja = "*"
pip = "*"
setuptools = "*"
wheel = "*"
